# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4554b09f0202d2efb8ae969abbdd1f6b65cf3eb76ef2d4b48a4fade47dfb3ed4f44246d2a362ba2a1a054a40d72e8a5b3884af9e5f95219ac32071d6c18e7a4f

test:
  secret_key_base: eb7d45cc08772f7fe90d72071f57112053a036b054796a606c8dccc464328f78e1a959d3ff2b325a588afcd543f33a8bd2283354e26e496dde4ecead2cd52711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
